### ISSUE TITLE
the tutorial link is broken

### ISSUE THREAD

**Issue by carlotarp** [genepattern/genepattern-python#2]
Could you fix it please? It would be very helpful to have a tutorial

Thanks
Carlota

**Comment by tmtabor** [comment]
I apologize for that. Earlier this week I restructured where we keep our example notebooks and apparently missed updating the link this this repository. I'll get it fixed in a minute. Meanwhile, you can find the GenePattern Python Tutorial here: https://github.com/genepattern/example-notebooks/blob/master/GenePattern%20Python%20Tutorial.ipynb
